In [3]:
import pandas as pd

In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
#Define the vocabulary size
voc_size = 10000

In [9]:
#One hot representation for every word
one_hot_repr = [one_hot(words, voc_size)for words in sent]
one_hot_repr

[[2532, 747, 5635, 8928],
 [2532, 747, 5635, 5015],
 [2532, 903, 5635, 3753],
 [6739, 3696, 4922, 6208, 7734],
 [6739, 3696, 4922, 6208, 273],
 [4151, 2532, 4750, 5635, 1345],
 [8296, 4679, 1811, 6208]]

In [10]:
# Word Embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [ ]:
# padding='pre' can also be 'post'
max_sentence_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=max_sentence_length)
print(embedded_docs)

[[   0    0    0    0 2532  747 5635 8928]
 [   0    0    0    0 2532  747 5635 5015]
 [   0    0    0    0 2532  903 5635 3753]
 [   0    0    0 6739 3696 4922 6208 7734]
 [   0    0    0 6739 3696 4922 6208  273]
 [   0    0    0 4151 2532 4750 5635 1345]
 [   0    0    0    0 8296 4679 1811 6208]]


In [14]:
## Feature representation
dimension = 10


In [15]:
model=Sequential()
model.add(Embedding(voc_size, dimension, input_length=max_sentence_length))
model.compile('adam', 'mse')

In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 76ms/step


array([[[ 4.4658218e-02,  3.4306381e-02,  2.9782582e-02, -1.6340684e-02,
          3.3250932e-02, -4.1321516e-02, -3.8832594e-02,  4.6024714e-02,
          1.9293156e-02, -3.0768467e-02],
        [ 4.4658218e-02,  3.4306381e-02,  2.9782582e-02, -1.6340684e-02,
          3.3250932e-02, -4.1321516e-02, -3.8832594e-02,  4.6024714e-02,
          1.9293156e-02, -3.0768467e-02],
        [ 4.4658218e-02,  3.4306381e-02,  2.9782582e-02, -1.6340684e-02,
          3.3250932e-02, -4.1321516e-02, -3.8832594e-02,  4.6024714e-02,
          1.9293156e-02, -3.0768467e-02],
        [ 4.4658218e-02,  3.4306381e-02,  2.9782582e-02, -1.6340684e-02,
          3.3250932e-02, -4.1321516e-02, -3.8832594e-02,  4.6024714e-02,
          1.9293156e-02, -3.0768467e-02],
        [ 1.4073398e-02,  2.5923733e-02, -2.8976953e-02,  2.9925514e-02,
         -4.2167209e-02,  3.0351568e-02, -4.5792770e-02,  8.2300194e-03,
         -5.1103532e-05, -1.0702670e-02],
        [-3.2292798e-02, -3.9931975e-02, -3.8408302e-02, -1.

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 2532,  747, 5635, 8928], dtype=int32)

In [19]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 27ms/step


array([[ 4.4658218e-02,  3.4306381e-02,  2.9782582e-02, -1.6340684e-02,
         3.3250932e-02, -4.1321516e-02, -3.8832594e-02,  4.6024714e-02,
         1.9293156e-02, -3.0768467e-02],
       [ 4.4658218e-02,  3.4306381e-02,  2.9782582e-02, -1.6340684e-02,
         3.3250932e-02, -4.1321516e-02, -3.8832594e-02,  4.6024714e-02,
         1.9293156e-02, -3.0768467e-02],
       [ 4.4658218e-02,  3.4306381e-02,  2.9782582e-02, -1.6340684e-02,
         3.3250932e-02, -4.1321516e-02, -3.8832594e-02,  4.6024714e-02,
         1.9293156e-02, -3.0768467e-02],
       [ 4.4658218e-02,  3.4306381e-02,  2.9782582e-02, -1.6340684e-02,
         3.3250932e-02, -4.1321516e-02, -3.8832594e-02,  4.6024714e-02,
         1.9293156e-02, -3.0768467e-02],
       [ 1.4073398e-02,  2.5923733e-02, -2.8976953e-02,  2.9925514e-02,
        -4.2167209e-02,  3.0351568e-02, -4.5792770e-02,  8.2300194e-03,
        -5.1103532e-05, -1.0702670e-02],
       [-3.2292798e-02, -3.9931975e-02, -3.8408302e-02, -1.4728438e-02,
   